### ISSUE TITLE
TODO before Release

### ISSUE THREAD

**Issue by erikwatson** [erikwatson/snowfall.js#39]
Some of these can probably be issues on here, but others are things to do elsewhere. 

- [ ] Update the Visual Config Editor 
- [ ] Update the Docs 
- [ ] Update the README
